{ config, lib, ... }:

# Hyprland 0.55 Lua configuration, generated by Nix.
#
# WHY THIS EXISTS (see docs/hyprland-lua-migration.md):
#   - Hyprland 0.55 deprecated hyprlang in favour of Lua; .lua is preferred over
#     .conf at startup, so this file shadows the still-generated hyprland.conf.
#   - The upstream `programs.hyprland` NixOS module only emits hyprlang, and the
#     home-manager `configType="lua"` generator is broken on `$variable`s
#     (nix-community/home-manager#9468). So we hand-author the Lua and use Nix
#     purely as the templating engine (stylix colours + the host prelude).
#
# COEXISTENCE: the hyprlang settings.nix/binds.nix/rules.nix are left intact as
# an instant rollback — delete this module (or the etc file) and the proven
# hyprland.conf takes over again.

let
  # Mirror settings.nix: stylix only exists on framework13; fall back to white.
  hasStylix = config ? lib && config.lib ? stylix;
  c = lib.optionalAttrs hasStylix config.lib.stylix.colors;
  active   = if hasStylix then "rgba(${c.base05}cc)" else "rgba(ffffffcc)";
  inactive = if hasStylix then "rgba(${c.base04}44)" else "rgba(ffffff44)";
in {
  # Host-specific Lua (monitors / devices / per-workspace monitor) injected near
  # the top of hyprland.lua. Default targets unknown hardware (phantom/live-iso);
  # framework13 overrides it. Adding sibling options under programs.hyprland is
  # fine — NixOS merges option declarations across modules.
  options.programs.hyprland.luaPrelude = lib.mkOption {
    type = lib.types.lines;
    default = ''
      -- Generic auto-detected display + tap-to-click for unknown touchpads.
      hl.monitor({ output = "", mode = "preferred", position = "auto", scale = 1 })
      hl.config({ input = { touchpad = { ["tap-to-click"] = true } } })
    '';
    description = ''
      Host-specific Lua appended after the variable block in hyprland.lua
      (monitors, per-device input, per-workspace monitor assignment).
    '';
  };

  config.environment.etc."xdg/hypr/hyprland.lua".text = ''
    -- GENERATED by system/programs/hyprland/lua.nix — do not edit by hand.
    -- Migrated from hyprlang; see docs/hyprland-lua-migration.md.
    -- Hyprland prefers this .lua over the (still-generated) hyprland.conf.

    --==============================================================
    -- Variables (were $mod / $menu / ... in hyprlang)
    --==============================================================
    local mod         = "SUPER"
    local menu        = "walker"
    local terminal    = "uwsm app -- ghostty"
    local fileManager = "uwsm app -- yazi"
    local browser     = "uwsm app -- firefox"
    local webapp      = browser .. " --new-tab"

    --==============================================================
    -- Host prelude (monitors / devices / workspace->monitor)
    --==============================================================
    ${config.programs.hyprland.luaPrelude}

    --==============================================================
    -- Environment
    --==============================================================
    hl.env("HYPRCURSOR_THEME", "rose-pine-hyprcursor")
    hl.env("HYPRCURSOR_SIZE", "24")

    --==============================================================
    -- Autostart (was exec-once)
    --==============================================================
    hl.on("hyprland.start", function()
      hl.exec_cmd("uwsm finalize")
      -- walker is owned by home-manager's walker.service; not started here.
      hl.exec_cmd("uwsm app -- waybar")
      hl.exec_cmd("uwsm app -- wl-paste --type text --watch cliphist store")
      hl.exec_cmd("uwsm app -- wl-paste --type image --watch cliphist store")
      hl.exec_cmd("hyprlock")
      hl.exec_cmd("uwsm app -- mako")
      hl.exec_cmd("fcitx5 -d --replace")
      -- boot straight into the ws1 notes layout (rules size firefox/obsidian)
      hl.exec_cmd("[workspace 1 silent] uwsm app -- firefox")
      hl.exec_cmd("[workspace 1 silent] uwsm app -- obsidian -disable-gpu")
    end)

    --==============================================================
    -- Keyword config (general / decoration / input / ...)
    --==============================================================
    hl.config({
      general = {
        gaps_in = 1,
        gaps_out = 0,
        border_size = 1,
        col = {
          active_border = "${active}",
          inactive_border = "${inactive}",
        },
        resize_on_border = false,
        allow_tearing = false,
        layout = "dwindle",
      },

      decoration = {
        rounding = 0,
        shadow = {
          enabled = false,
          range = 4,
          render_power = 3,
          color = "rgba(00000055)",
        },
        blur = {
          enabled = false,
          size = 6,
          passes = 1,
          ignore_opacity = true,
          new_optimizations = true,
          special = true,
          popups = true,
          vibrancy = 0.1696,
        },
      },

      cursor = {
        no_hardware_cursors = false,
        hide_on_key_press = true,
      },

      master = {
        mfact = 0.60,
        new_status = "slave",
        new_on_top = false,
        allow_small_split = true,
        orientation = "center",
        slave_count_for_center_master = 2,
        center_master_fallback = "left",
      },

      dwindle = {
        preserve_split = true,
        force_split = 2,
        smart_split = false,
      },

      scrolling = {
        column_width = 0.5,
        fullscreen_on_one_column = true,
        follow_focus = true,
        wrap_focus = true,
        explicit_column_widths = "0.333, 0.5, 0.667, 1.0",
      },

      misc = {
        force_default_wallpaper = 0,
        enable_swallow = true,
        swallow_regex = "^(com.mitchellh.ghostty)$",
      },

      input = {
        kb_layout = "us",
        follow_mouse = 1,
        sensitivity = 0,
        touchpad = {
          natural_scroll = true,
          disable_while_typing = true,
        },
      },

      group = {
        auto_group = false,
        groupbar = {
          enabled = true,
          font_size = 10,
          height = 18,
          rounding = 0,
          render_titles = true,
          scrolling = true,
          col = {
            active = "${active}",
            inactive = "${inactive}",
            locked_active = "${active}",
            locked_inactive = "${inactive}",
          },
        },
        col = {
          border_active = "${active}",
          border_inactive = "${inactive}",
          border_locked_active = "${active}",
          border_locked_inactive = "${inactive}",
        },
      },

      binds = {
        window_direction_monitor_fallback = false,
        allow_workspace_cycles = true,
      },

      animations = {
        enabled = false,
      },
    })

    --==============================================================
    -- Gestures (was: "3, left, dispatcher, layoutmsg, move +col")
    -- No dispatcher gesture-action exists; use a Lua-function action.
    --==============================================================
    hl.gesture({ fingers = 3, direction = "left",  action = function() hl.dispatch(hl.dsp.layout("move +col")) end })
    hl.gesture({ fingers = 3, direction = "right", action = function() hl.dispatch(hl.dsp.layout("move -col")) end })

    --==============================================================
    -- Mouse binds (was bindm)
    --==============================================================
    hl.bind(mod .. " + mouse:272", hl.dsp.window.drag(),         { mouse = true })
    hl.bind(mod .. " + mouse:273", hl.dsp.window.resize(),       { mouse = true })
    hl.bind(mod .. " + ALT + mouse:272", hl.dsp.window.resize(), { mouse = true })

    --==============================================================
    -- Keybinds (was bind)
    --==============================================================
    -- compositor
    hl.bind(mod .. " + CTRL + ALT + Q", hl.dsp.exit())
    hl.bind(mod .. " + Q", hl.dsp.window.close())
    hl.bind(mod .. " + SHIFT + ESCAPE", hl.dsp.exec_cmd("systemctl suspend"))
    hl.bind(mod .. " + SHIFT + CTRL + ESCAPE", hl.dsp.exec_cmd("systemctl poweroff"))

    -- tiling control
    hl.bind(mod .. " + SHIFT + F", hl.dsp.window.fullscreen({ action = "toggle" }))
    hl.bind(mod .. " + G", hl.dsp.group.toggle())
    hl.bind(mod .. " + F", hl.dsp.window.float({ action = "toggle" }))
    hl.bind(mod .. " + T", hl.dsp.layout("togglesplit"))    -- dwindle
    hl.bind(mod .. " + SHIFT + P", hl.dsp.window.pseudo())  -- dwindle
    hl.bind(mod .. " + SHIFT + C", hl.dsp.window.center())
    hl.bind(mod .. " + P", hl.dsp.window.pin({ action = "toggle" }))
    hl.bind(mod .. " + D", hl.dsp.focus({ urgent_or_last = true }))

    -- group navigation
    hl.bind(mod .. " + TAB", hl.dsp.group.next())
    hl.bind(mod .. " + SHIFT + TAB", hl.dsp.group.prev())
    hl.bind(mod .. " + CTRL + G", hl.dsp.window.move({ out_of_group = true }))
    -- lockgroups (all groups) has no typed helper; use the hyprctl fallback.
    hl.bind(mod .. " + ALT + G", hl.dsp.exec_cmd("hyprctl dispatch lockgroups toggle"))

    -- utilities
    hl.bind(mod .. " + RETURN", hl.dsp.exec_cmd(terminal))
    hl.bind(mod .. " + y", hl.dsp.exec_cmd(fileManager))
    hl.bind(mod .. " + SPACE", hl.dsp.exec_cmd(menu))
    hl.bind(mod .. " + CTRL + Q", hl.dsp.exec_cmd("hyprlock"))

    -- walker providers
    hl.bind(mod .. " + CTRL + V", hl.dsp.exec_cmd("walker -m clipboard"))
    hl.bind(mod .. " + W", hl.dsp.exec_cmd("walker -m windows"))
    hl.bind(mod .. " + CTRL + period", hl.dsp.exec_cmd("walker -m symbols"))
    hl.bind(mod .. " + CTRL + N", hl.dsp.exec_cmd("walker -m todo"))

    -- keybind cheatsheet
    hl.bind(mod .. " + slash", hl.dsp.exec_cmd("hypr-binds-menu"))

    -- notifications: DND toggle + history centre
    hl.bind(mod .. " + SHIFT + D", hl.dsp.exec_cmd("makoctl mode -t dnd; pkill -RTMIN+9 waybar"))
    hl.bind(mod .. " + CTRL + D", hl.dsp.exec_cmd("mako-history-menu"))

    -- move focus (h/l directional, j/k sequential)
    hl.bind(mod .. " + h", hl.dsp.focus({ direction = "left" }))
    hl.bind(mod .. " + l", hl.dsp.focus({ direction = "right" }))
    hl.bind(mod .. " + k", hl.dsp.focus({ direction = "up" }))
    hl.bind(mod .. " + j", hl.dsp.focus({ direction = "down" }))

    -- cycle windows (mod+TAB reserved for groups)
    hl.bind("ALT + TAB", hl.dsp.window.cycle_next())
    hl.bind("ALT + SHIFT + TAB", hl.dsp.window.cycle_next({ next = false }))

    -- move window or group (swap tiled, merge/unmerge groups)
    hl.bind(mod .. " + SHIFT + h", hl.dsp.window.move({ direction = "l", group_aware = true }))
    hl.bind(mod .. " + SHIFT + l", hl.dsp.window.move({ direction = "r", group_aware = true }))
    hl.bind(mod .. " + SHIFT + k", hl.dsp.window.move({ direction = "u", group_aware = true }))
    hl.bind(mod .. " + SHIFT + j", hl.dsp.window.move({ direction = "d", group_aware = true }))

    -- cycle workspaces
    hl.bind(mod .. " + bracketleft", hl.dsp.focus({ workspace = "m-1" }))
    hl.bind(mod .. " + bracketright", hl.dsp.focus({ workspace = "m+1" }))
    hl.bind(mod .. " + ESCAPE", hl.dsp.focus({ workspace = "previous" }))

    -- cycle monitors
    hl.bind(mod .. " + SHIFT + bracketleft", hl.dsp.focus({ monitor = "l" }))
    hl.bind(mod .. " + SHIFT + bracketright", hl.dsp.focus({ monitor = "r" }))

    -- send focused workspace to left/right monitor
    hl.bind(mod .. " + SHIFT + ALT + bracketleft", hl.dsp.workspace.move({ monitor = "l" }))
    hl.bind(mod .. " + SHIFT + ALT + bracketright", hl.dsp.workspace.move({ monitor = "r" }))

    -- master: promote to master
    hl.bind(mod .. " + CTRL + RETURN", hl.dsp.layout("swapwithmaster master"))

    -- column resize (cycles explicit_column_widths) — scrolling
    hl.bind(mod .. " + equal", hl.dsp.layout("colresize +conf"))
    hl.bind(mod .. " + minus", hl.dsp.layout("colresize -conf"))
    hl.bind(mod .. " + SHIFT + SPACE", hl.dsp.layout("orientationnext"))
    hl.bind(mod .. " + CTRL + SHIFT + SPACE", hl.dsp.layout("orientationprev"))

    -- scroll layout
    hl.bind(mod .. " + c", hl.dsp.layout("fit active"))
    hl.bind(mod .. " + SHIFT + c", hl.dsp.layout("fit visible"))
    hl.bind(mod .. " + CTRL + c", hl.dsp.layout("fit all"))
    hl.bind(mod .. " + period", hl.dsp.layout("move +col"))
    hl.bind(mod .. " + comma", hl.dsp.layout("move -col"))

    -- theme toggle
    hl.bind(mod .. " + F5", hl.dsp.exec_cmd("theme-switch"))

    -- screenshot (grim+satty)
    hl.bind("SHIFT + Print", hl.dsp.exec_cmd("screenshot area"))
    hl.bind("Print", hl.dsp.exec_cmd("screenshot full"))

    -- screen recording (toggle)
    hl.bind(mod .. " + Print", hl.dsp.exec_cmd("wf-recorder-toggle"))
    hl.bind(mod .. " + SHIFT + Print", hl.dsp.exec_cmd("wf-recorder-toggle area"))

    -- special workspaces
    hl.bind(mod .. " + M", hl.dsp.workspace.toggle_special("chat"))
    hl.bind(mod .. " + SHIFT + M", hl.dsp.window.move({ workspace = "special:chat" }))
    hl.bind(mod .. " + B", hl.dsp.workspace.toggle_special("work"))
    hl.bind(mod .. " + SHIFT + B", hl.dsp.window.move({ workspace = "special:work" }))

    -- z-order management for floating windows
    hl.bind(mod .. " + ALT + k", hl.dsp.window.alter_zorder({ mode = "top" }))
    hl.bind(mod .. " + ALT + j", hl.dsp.window.alter_zorder({ mode = "bottom" }))

    -- workspaces 1..10 (was the Nix genList): switch / move / move-silent
    for i = 1, 10 do
      local key = i % 10  -- 10 maps to key 0
      hl.bind(mod .. " + " .. key, hl.dsp.focus({ workspace = i }))
      hl.bind(mod .. " + SHIFT + " .. key, hl.dsp.window.move({ workspace = i }))
      hl.bind(mod .. " + CTRL + " .. key, hl.dsp.window.move({ workspace = i, follow = false }))
    end

    --==============================================================
    -- Locked / repeating media + brightness keys (was bindle / bindl)
    --==============================================================
    hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+"), { locked = true, repeating = true })
    hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"), { locked = true, repeating = true })
    hl.bind("XF86AudioMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"), { locked = true, repeating = true })
    hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"), { locked = true, repeating = true })
    hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("brightnessctl -c backlight s 10%+"), { locked = true, repeating = true })
    hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl -c backlight s 10%-"), { locked = true, repeating = true })

    hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"), { locked = true })
    hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
    hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
    hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"), { locked = true })

    --==============================================================
    -- Submaps (were `submap=...` blocks in extraConfig)
    --==============================================================

    -- resize: sticky mode, repeatable; exit with escape/return
    hl.bind(mod .. " + R", hl.dsp.submap("resize"))
    hl.define_submap("resize", function()
      hl.bind("h", hl.dsp.window.resize({ x = -100, y = 0, relative = true }), { repeating = true })
      hl.bind("l", hl.dsp.window.resize({ x = 100, y = 0, relative = true }), { repeating = true })
      hl.bind("k", hl.dsp.window.resize({ x = 0, y = -100, relative = true }), { repeating = true })
      hl.bind("j", hl.dsp.window.resize({ x = 0, y = 100, relative = true }), { repeating = true })
      hl.bind("escape", hl.dsp.submap("reset"))
      hl.bind("RETURN", hl.dsp.submap("reset"))
    end)

    -- launch: auto-resets to global after each action (3rd arg = "reset")
    hl.bind(mod .. " + X", hl.dsp.submap("launch"))
    hl.define_submap("launch", "reset", function()
      hl.bind("A", hl.dsp.exec_cmd(webapp .. " https://openrouter.ai/chat"))
      hl.bind("B", hl.dsp.exec_cmd(browser))
      hl.bind("C", hl.dsp.exec_cmd(webapp .. " https://app.hey.com/calendar/weeks/"))
      hl.bind("D", hl.dsp.exec_cmd(terminal .. " -e lazydocker"))
      hl.bind("E", hl.dsp.exec_cmd(webapp .. " https://app.hey.com"))
      hl.bind("O", hl.dsp.exec_cmd("uwsm app -- obsidian -disable-gpu"))
      hl.bind("R", hl.dsp.exec_cmd(terminal .. " -e newsboat"))
      hl.bind("slash", hl.dsp.exec_cmd("uwsm app -- keepassxc"))
      hl.bind("escape", hl.dsp.submap("reset"))
    end)

    -- place: snap floating windows to zones; stays active for multiple placements.
    -- The batch pixel commands have no typed helper, so keep the hyprctl form.
    hl.bind(mod .. " + V", hl.dsp.submap("place"))
    hl.define_submap("place", function()
      -- halves
      hl.bind("h", hl.dsp.exec_cmd([[hyprctl --batch "dispatch setfloating ; dispatch resizewindowpixel exact 50% 100% ; dispatch movewindowpixel exact 0 0"]]))
      hl.bind("l", hl.dsp.exec_cmd([[hyprctl --batch "dispatch setfloating ; dispatch resizewindowpixel exact 50% 100% ; dispatch movewindowpixel exact 50% 0"]]))
      hl.bind("k", hl.dsp.exec_cmd([[hyprctl --batch "dispatch setfloating ; dispatch resizewindowpixel exact 100% 50% ; dispatch movewindowpixel exact 0 0"]]))
      hl.bind("j", hl.dsp.exec_cmd([[hyprctl --batch "dispatch setfloating ; dispatch resizewindowpixel exact 100% 50% ; dispatch movewindowpixel exact 0 50%"]]))
      -- center variants
      hl.bind("c", hl.dsp.exec_cmd([[hyprctl --batch "dispatch setfloating ; dispatch resizewindowpixel exact 70% 70% ; dispatch centerwindow"]]))
      hl.bind("f", hl.dsp.exec_cmd([[hyprctl --batch "dispatch setfloating ; dispatch resizewindowpixel exact 95% 95% ; dispatch centerwindow"]]))
      hl.bind("m", hl.dsp.exec_cmd([[hyprctl --batch "dispatch setfloating ; dispatch resizewindowpixel exact 50% 50% ; dispatch centerwindow"]]))
      -- quadrants
      hl.bind("1", hl.dsp.exec_cmd([[hyprctl --batch "dispatch setfloating ; dispatch resizewindowpixel exact 50% 50% ; dispatch movewindowpixel exact 0 0"]]))
      hl.bind("2", hl.dsp.exec_cmd([[hyprctl --batch "dispatch setfloating ; dispatch resizewindowpixel exact 50% 50% ; dispatch movewindowpixel exact 50% 0"]]))
      hl.bind("3", hl.dsp.exec_cmd([[hyprctl --batch "dispatch setfloating ; dispatch resizewindowpixel exact 50% 50% ; dispatch movewindowpixel exact 0 50%"]]))
      hl.bind("4", hl.dsp.exec_cmd([[hyprctl --batch "dispatch setfloating ; dispatch resizewindowpixel exact 50% 50% ; dispatch movewindowpixel exact 50% 50%"]]))
      -- incremental move (repeatable)
      hl.bind("SHIFT + h", hl.dsp.window.move({ x = -40, y = 0, relative = true }), { repeating = true })
      hl.bind("SHIFT + l", hl.dsp.window.move({ x = 40, y = 0, relative = true }), { repeating = true })
      hl.bind("SHIFT + k", hl.dsp.window.move({ x = 0, y = -40, relative = true }), { repeating = true })
      hl.bind("SHIFT + j", hl.dsp.window.move({ x = 0, y = 40, relative = true }), { repeating = true })
      -- incremental resize (repeatable)
      hl.bind("equal", hl.dsp.window.resize({ x = 40, y = 40, relative = true }), { repeating = true })
      hl.bind("minus", hl.dsp.window.resize({ x = -40, y = -40, relative = true }), { repeating = true })
      hl.bind("escape", hl.dsp.submap("reset"))
      hl.bind("RETURN", hl.dsp.submap("reset"))
    end)

    -- vim-style window marks: mod+N <letter> sets, mod+' <letter> jumps.
    -- Both auto-reset to global after each letter (3rd arg = "reset").
    local markLetters = "abcdefghijklmnopqrstuvwxyz"

    hl.bind(mod .. " + N", hl.dsp.submap("mark"))
    hl.define_submap("mark", "reset", function()
      for ch in markLetters:gmatch(".") do
        hl.bind(ch, hl.dsp.exec_cmd("hypr-mark set " .. ch))
      end
      hl.bind("escape", hl.dsp.submap("reset"))
    end)

    hl.bind(mod .. " + apostrophe", hl.dsp.submap("jump"))
    hl.define_submap("jump", "reset", function()
      for ch in markLetters:gmatch(".") do
        hl.bind(ch, hl.dsp.exec_cmd("hypr-mark jump " .. ch))
      end
      hl.bind("escape", hl.dsp.submap("reset"))
    end)

    --==============================================================
    -- Window rules (was windowrule = [...] with match: syntax)
    --==============================================================
    -- Tags
    hl.window_rule({ match = { class = "^([Ff]irefox|org.mozilla.firefox|[Ff]irefox-esr|[Ff]irefox-bin)$" }, tag = "+browser" })
    hl.window_rule({ match = { class = "^([Gg]oogle-chrome(-beta|-dev|-unstable)?)$" }, tag = "+browser" })
    hl.window_rule({ match = { class = "^([Cc]hromium)$" }, tag = "+browser" })
    hl.window_rule({ match = { class = "^([Cc]hromium-browser)$" }, tag = "+browser" })
    hl.window_rule({ match = { class = "^(com.mitchellh.ghostty)$" }, tag = "+terminal" })
    hl.window_rule({ match = { class = "^([Tt]hunderbird)$" }, tag = "+im-work" })
    hl.window_rule({ match = { class = "^([Ss]lack)$" }, tag = "+im-work" })
    hl.window_rule({ match = { class = "^([Dd]iscord).*$" }, tag = "+im" })
    hl.window_rule({ match = { class = "^(org.telegram.desktop)$" }, tag = "+im" })
    hl.window_rule({ match = { class = "^([Ss]ignal)$" }, tag = "+im" })
    hl.window_rule({ match = { class = "^([Tt]hunar|org.gnome.Nautilus)$" }, tag = "+file-manager" })
    hl.window_rule({ match = { class = "^(firefox)$", title = "^(Picture-in-Picture)$" }, tag = "+pip" })
    hl.window_rule({ match = { class = "^(org.keepassxc.KeePassXC)$" }, tag = "+passwd" })

    hl.window_rule({ match = { class = ".*" }, suppress_event = "maximize" })
    hl.window_rule({ match = { class = "^$", title = "^$", xwayland = true, float = true, fullscreen = false, pin = false }, no_focus = true })

    -- Opacity (was `opacity 1.0 0.97, match:tag *` — apply to all windows)
    hl.window_rule({ match = { class = ".*" }, opacity = "1.0 0.97" })
    hl.window_rule({ match = { tag = "file-manager" }, opacity = "0.97 0.8" })

    hl.window_rule({ match = { tag = "im-work" }, workspace = "special:work" })
    hl.window_rule({ match = { tag = "im" }, workspace = "special:chat" })

    -- notes = obsidian beside firefox on ws1
    hl.window_rule({ match = { tag = "browser" }, workspace = "1" })
    hl.window_rule({ match = { class = "^(obsidian)$" }, workspace = "1" })

    hl.window_rule({ match = { title = "^(Grayjay)$" }, float = false })
    hl.window_rule({ match = { title = "^(Grayjay)$" }, workspace = "4" })

    -- Picture-in-Picture
    hl.window_rule({ match = { initial_title = "^Picture-in-Picture$" }, opacity = "1 1" })
    hl.window_rule({ match = { tag = "pip" }, float = true })
    hl.window_rule({ match = { tag = "pip" }, pin = true })
    hl.window_rule({ match = { tag = "pip" }, no_focus = true })
    hl.window_rule({ match = { tag = "pip" }, size = "300 169" })
    hl.window_rule({ match = { tag = "pip" }, move = "100%-320 100%-190" })
    hl.window_rule({ match = { tag = "pip" }, keep_aspect_ratio = true })

    -- KeePassXC
    hl.window_rule({ match = { tag = "passwd" }, float = true })
    hl.window_rule({ match = { tag = "passwd" }, center = true })
    hl.window_rule({ match = { tag = "passwd" }, size = "60% 70%" })

    hl.window_rule({ match = { tag = "terminal" }, tile = true })

    -- Scrolling layout column widths
    hl.window_rule({ match = { class = "^(obsidian)$" }, scrolling_width = 0.333 })
    hl.window_rule({ match = { tag = "terminal" }, scrolling_width = 0.5 })
    hl.window_rule({ match = { tag = "browser" }, scrolling_width = 0.667 })
    hl.window_rule({ match = { tag = "im-work" }, scrolling_width = 0.333 })
    hl.window_rule({ match = { tag = "im" }, scrolling_width = 0.5 })

    -- Screen sharing
    hl.window_rule({ match = { tag = "im" }, no_screen_share = true })
    hl.window_rule({ match = { tag = "im-work" }, no_screen_share = true })
    hl.window_rule({ match = { tag = "passwd" }, no_screen_share = true })

    hl.window_rule({ match = { class = "([Tt]hunar)", title = "negative:(.*[Tt]hunar.*)" }, center = true })

    -- satty annotation editor
    hl.window_rule({ match = { class = "^(com.gabm.satty)$" }, float = true })
    hl.window_rule({ match = { class = "^(com.gabm.satty)$" }, size = "80% 80%" })
    hl.window_rule({ match = { class = "^(com.gabm.satty)$" }, center = true })

    -- Smart borders: no border/rounding with one tiled window
    hl.window_rule({ match = { float = false, workspace = "w[tv1]" }, border_size = 0 })
    hl.window_rule({ match = { float = false, workspace = "w[tv1]" }, rounding = 0 })
    hl.window_rule({ match = { float = false, workspace = "f[1]" }, border_size = 0 })
    hl.window_rule({ match = { float = false, workspace = "f[1]" }, rounding = 0 })

    -- Dialog windows: float + center (was the Nix dialogRules)
    local dialogTitles = { "Open File", "Select a File", "Choose wallpaper", "Open Folder", "Save As", "Library", "File Upload" }
    for _, t in ipairs(dialogTitles) do
      hl.window_rule({ match = { title = "^(" .. t .. ")(.*)$" }, float = true })
      hl.window_rule({ match = { title = "^(" .. t .. ")(.*)$" }, center = true })
    end

    --==============================================================
    -- Workspace rules (was workspace = [...])
    --==============================================================
    -- Per-workspace layouts
    hl.workspace_rule({ workspace = "1", layout = "scrolling" })
    hl.workspace_rule({ workspace = "2", layout = "master" })
    hl.workspace_rule({ workspace = "3", layout = "dwindle" })
    hl.workspace_rule({ workspace = "4", layout = "scrolling" })
    hl.workspace_rule({ workspace = "5", layout = "scrolling" })
    hl.workspace_rule({ workspace = "special:work", layout = "scrolling" })
    hl.workspace_rule({ workspace = "special:chat", layout = "scrolling" })

    hl.workspace_rule({ workspace = "special:work", gaps_out = 40, gaps_in = 10 })
    hl.workspace_rule({ workspace = "special:chat", gaps_out = 40, gaps_in = 10 })

    -- Smart gaps: none when only one tiled/fullscreen window
    hl.workspace_rule({ workspace = "w[tv1]", gaps_out = 0, gaps_in = 0 })
    hl.workspace_rule({ workspace = "f[1]", gaps_out = 0, gaps_in = 0 })
  '';
}
