# SOPS configuration for encrypting secrets
# See: https://github.com/getsops/sops
keys:
  - &framework13 age1hd4y0v9k4ng3xkmprgvvnxzm6wh72k9lrr2smjerwkkn7q5j4ers2e83wf
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    age:
    - *framework13
