# SOPS configuration for encrypting secrets
# See: https://github.com/getsops/sops
keys:
  # Host keys (software)
  - &framework13 age1hd4y0v9k4ng3xkmprgvvnxzm6wh72k9lrr2smjerwkkn7q5j4ers2e83wf
  - &steamdeck age1vc06cssvpwyc8m97yylevnm608z32um2cx4khjl2qt3nrmhqh57srkvcnt
  # YubiKey keys (hardware)
  - &yubikey2 age1yubikey1qd47xas9v304svawpqex2s0xpaa0yfmla6vsssq65tn4ey4zaxk9u7zwjcq
  # Future hosts:
  # - &zimaboard age1...

creation_rules:
  # Common secrets - encrypted to all hosts
  - path_regex: secrets/common/.*\.(yaml|json|env|ini)$
    age:
      - *framework13
      - *yubikey2

  # Framework13-specific secrets
  - path_regex: secrets/framework13/.*\.(yaml|json|env|ini)$
    age:
      - *framework13
      - *yubikey2

  # ISO-specific secrets (YubiKey-only, portable across machines)
  - path_regex: secrets/iso/.*\.(yaml|json|env|ini)$
    age:
      - *yubikey2

  # Steam Deck-specific secrets
  - path_regex: secrets/steamdeck/.*\.(yaml|json|env|ini)$
    age:
      - *steamdeck

  # Future: ZimaBoard-specific secrets
  # - path_regex: secrets/zimaboard/.*\.(yaml|json|env|ini)$
  #   age:
  #     - *zimaboard
